### ISSUE TITLE
Permalink to archive from search results

### ISSUE THREAD

**Issue by srid** [srid/Taut#11]
Clicking on a message from the search results should take us directly to the message located in its per-day Archive page. If the archive link has multiple pages ([example](https://slackarchive.actualists.org/messages/2016/8/12?page=2)), then it should take us to the corresponding page. 

- [x] Clicking link to take us to the associated archive day (page 1)
- [ ] Take directly to nth page where message is located
- [ ] Automatically scroll to and highlight the message

Requested by @Narrowboater

**Comment by Narrowboater** [comment]
Clicking on the message doesn’t work for me Srid - maybe because it’s the iPad though I don’t seewhy that would be so. Also clicking on your “example” gets a server not found message. Sorry.

**Comment by srid** [comment]
@Narrowboater The link was wrong; I've fixed it now; try again.

**Comment by Narrowboater** [comment]
The link works now but I am not sure what the example is supposed to demonstrate. I still don’t get anything by clicking on the message.

**Comment by srid** [comment]
This is basically done, and will be improved further as part of #13.

**Comment by Narrowboater** [comment]
Any chance of being able to search from a date? I know I’m demanding lol.
